MyDiplom/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('orders/', include('orders.urls')),
]

MyDiplom/orders/urls.py
"""Определяет схемы URL для orders."""

from django.urls import path
from . import views
from orders.views import OrderCreateView, SuccessView, OrderListView, OrderDetailView

app_name = 'orders'

urlpatterns = [
    # Страница заказов
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('payment/', views.full_fill_order, name='payment'),
    path('success/', SuccessView.as_view(), name='success'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
]

MyDiplom/products/urls.py
"""Определяет схемы URL для products."""

from django.urls import path
from . import views
from .views import MainPageView, ProductsListView, CatalogsListView

app_name = 'products'

urlpatterns = [
    # Домашняя страница
    # path('', views.main_page, name='main_page'),
    path('', MainPageView.as_view(), name='main_page'),
    # Страница каталога продуктов
    path('catalogs/', CatalogsListView.as_view(), name='catalogs'),
    path('products/<int:catalog_id>/', ProductsListView.as_view(), name='products'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    # Страница о магазине
    path('about_us/', views.about_us, name='about_us'),
    # Страница с контактами
    path('contacts/', views.contacts, name='contacts'),
    # Страница корзины
    path('basket/', views.basket, name='basket'),
    path('baskets/add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', views.basket_remove, name='basket_remove'),
]

MyDiplom/users/urls.py
"""Определяет схемы URL для пользователей."""
from django.urls import path
from .views import registerUser, profile, login, user_logout

app_name = 'users'

urlpatterns = [
    # Странички авторизации и выхода.
    path('login/', login, name='login'),
    path('logout/', user_logout, name='logout'),
    # Страницы регистрации и профиля.
    path('register/', registerUser, name='register'),
    path('profile/', profile, name='profile'),
]

MyDiplom/products/models.py
from django.db import models


class Catalog(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'catalog'

    def __str__(self):
        return f'{self.name}'



class Product(models.Model):
    id = models.SmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.CharField(max_length=100)
    catalog = models.ForeignKey(Catalog, models.CASCADE)

    class Meta:
        db_table = 'product'

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.catalog.name}'



class Basket(models.Model):
    id = models.IntegerField(primary_key=True)
    created = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'basket'

    def __str__(self):
        return f'{self.id} {self.created}'



class BasketItem(models.Model):
    basket = models.OneToOneField(Basket, models.CASCADE, primary_key=True)
    product = models.ForeignKey('Product', models.CASCADE)
    quantity = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'basket_item'
        unique_together = (('basket', 'product'),)

    def __str__(self):
        return f'{self.product} {self.quantity}'

MyDiplom/products/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from .models import Catalog, Product
from .models import Basket
from django.shortcuts import render, HttpResponseRedirect



class MainPageView(TemplateView):
    """Домашняя страница интернет-магазина."""
    template_name = 'main_page.html'



class CatalogsListView(ListView):
    """Выводит каталоги продуктов."""
    model = Catalog
    template_name = 'catalogs.html'


# def products(request, catalog_id=None, page_number=1):
#     """Выводит определенный каталог продуктов."""
#     # catalog = Catalog.objects.get(id=catalog_id)
#     products = Product.objects.filter(catalog_id=catalog_id) if catalog_id else Product.objects.all()
#     per_page = 3
#     paginator = Paginator(products, per_page)
#     products_paginator = paginator.page(page_number)
#     # context = {'catalog': catalog, 'products': products_paginator}
#     context = {'products': products_paginator}
#     return render(request, 'products.html', context)



class ProductsListView(ListView):
    model = Product
    template_name = 'products.html'
    paginate_by = 5

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        catalog_id = self.kwargs.get('catalog_id')
        return queryset.filter(catalog_id=catalog_id) if catalog_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['catalogs'] = Catalog.objects.all()
        return context



def about_us(request):
    """Выводит страничку о продавце."""
    return render(request, 'about_us.html')



def contacts(request):
    """Выводит страничку с контактами магазина."""
    return render(request, 'contacts.html')



def basket(request):
    """Выводит страничку с корзиной."""
    baskets = Basket.objects.filter(user=request.user)
    total_sum = sum(basket.sum() for basket in baskets)
    total_quantity = sum(basket.quantity for basket in baskets)
    context = {'baskets': baskets, 'total_sum': total_sum, 'total_quantity': total_quantity}
    return render(request, 'basket.html', context)



@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])



@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    q = basket.quantity
    if q > 1:
        Basket.objects.filter(id=basket_id).update(quantity=q-1)
    else:
        basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

MyDiplom/products/templates/about_us.html
{% extends "base.html" %}

{% block content %}
<div>
    <img class="pic" src="/static/img/about.png">
    <p class="about"> Заметка о магазине или об авторе проекта. </p>
</div>
{% endblock content %}

MyDiplom/products/templates/base.html
{% load static %}


<html>
 <head>
   <title>Store</title>
   <link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet">

   <link href="{% static 'css/main_style.css' %}" rel="stylesheet">
 </head>
<body>
  <header>
    <h1 style="font-weight:bolder">STORE</h1>
    <nav>
      <ul class="menu">
        <li>
          <a href="{% url 'products:main_page' %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Главная</a>
        </li>
        <li>
          <a href="{% url 'products:catalogs' %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Каталог</a>
        </li>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'users:logout' %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Выйти</a>
        </li>
        {% else %}
        <li>
          <a href="{% url 'users:login' %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Вход</a>
        </li>
        {% endif %}
         {% if user.is_authenticated %}
        <li>
          <div class="btn-group" role="group">
              <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </button>
              <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                <a class="dropdown-item" href="{% url 'products:basket' %}">Корзина {% if baskets %} ({{ baskets.total_quantity }}) {% else %} {% endif %}</a>
                <a class="dropdown-item" href="{% url 'orders:orders' %}">Заказы</a>
              </div>
          </div>
        {% endif %}
      </ul>
    </nav>
  </header>

  <hr>

  <div class="content">
  {% block content %}{% endblock content %}
  </div>

  <hr>

  <footer>
    <ul class="menu">
      <li><a href="{% url 'products:about_us' %}">О нас</a></li>
      <li><a href="{% url 'products:contacts' %}">Контакты</a></li>
      <li>&copy; 2023 Python-project, Kuzmenko D.V.</li>
    </ul>

  </footer>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

MyDiplom/products/templates/basket.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center">
    {% include 'baskets.html' %}
</div>
{% endblock content %}

MyDiplom/products/templates/baskets.html
{% if baskets %}
    <div class="col-lg-5">
            <h4 class="mt-3 mb-3 mt-3 mb-3 text-center">
                Корзина ({{ user.first_name }} {{ user.last_name }}) <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
            </h4>
            {% for basket in baskets %}
                 <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'products:basket_remove' basket.id %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">
                                    Удалить
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            {% endfor%}

            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого</p>
                    <h4 class="float-right">{{ total_sum }} руб.</h4>
                </div>
            </div>
            <a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
                Оформить заказ
            </a>
    </div>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
                Корзина ({{ user.first_name }} {{ user.last_name }}) пуста
    </h4>
{% endif %}

MyDiplom/products/templates/catalogs.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="row justify-content-center">
    <h3>Каталоги продуктов:</h3>
    <ul>
        {% for catalog in object_list %}
        <li><a href="{% url 'products:products' catalog.id %}">{{ catalog }}
<!--            <img class="calalog" src="{% static 'img/ball.png' %}" alt="альтернативный текст">-->
            </a>
        </li>
        {% empty %}
        <li>No catalogs have been added yet.</li>
        {% endfor %}
    </ul>
</div>

{% endblock content %}

MyDiplom/products/templates/contacts.html
{% extends "base.html" %}

{% block content %}

<div>
    <img class="pic" src="/static/img/about.png">
    <h2>Наши контакты:</h2>
    <p></p>
    <p class="contacts"> email: anything@mail.ru </p>
    <p class="contacts"> телефон(сотовый): 8(922)277777 </p>
</div>

{% endblock content %}

MyDiplom/products/templates/main_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row justify-content-center">
    <h2 class="slogan">⫷ Игрушки с душой и для души. Oни поделятся с вами любовью ⫸</h2>
        <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="/static/slide/1.JPG"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/slide/2.JPG"
                                 alt="Second slide">
                        </div>
<!--                        <div class="carousel-item">-->
<!--                            <img class="d-block img-fluid" src="/static/slide/1 (2).JPG"-->
<!--                                 alt="Third slide">-->
<!--                        </div>-->
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
         </div>
</div>


{% endblock content %}

MyDiplom/products/templates/products.html
{% extends "base.html" %}


{% block content %}
<p>Каталог</p>

<div class="row justify-content-center">

     {% for product in object_list %}

    <div>
          <h4 class="text-center">{{ product.name }}</h4>
          <img class="picture" src="{{ product.image }}" alt="#" style="border-radius: 40px; width: 200px; height: 300px">
          <h3>{{ product.price }} ₽</h3>
          <p>{{ product.description }}</p>
          {% if user.is_authenticated %}

          <form method="POST" action="{% url 'products:basket' %}">
              {% csrf_token %}
              <input type="hidden" value="{{ product.id }}" name="product_id"/>
              <input type="hidden" value="{{ product.name }}" name="product_name"/>

              <a href="{% url 'products:basket_add' product.id %}" class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">Добавить в корзину</a>
          </form>
          {% endif %}
        </div>

     {% empty %}

    <div>No products have been added yet.</div>
     {% endfor %}

 </div>
     {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                                <a class="page-link"
                                   href="{% if page_obj.has_previous %} {% url 'products:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                                   tabindex="-1" aria-disabled="true">
                                    Предыдущая
                                </a>
                            </li>
                            {% for page in paginator.page_range %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'products:paginator' page %}">
                                        {{ page }}
                                    </a>
                                </li>
                            {% endfor %}
                            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                                <a class="page-link"
                                   href="{% if page_obj.has_next %} {% url 'products:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                                    Следующая
                                </a>
                            </li>
                        </ul>
                    </nav>
    {% endif %}




















{% endblock content %}