MyDiplom/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('orders/', include('orders.urls')),
]

MyDiplom/orders/urls.py
"""Определяет схемы URL для orders."""

from django.urls import path
from . import views
from orders.views import OrderCreateView, SuccessView, OrderListView, OrderDetailView

app_name = 'orders'

urlpatterns = [
    # Страница заказов
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('payment/', views.full_fill_order, name='payment'),
    path('success/', SuccessView.as_view(), name='success'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),
]

MyDiplom/products/urls.py
"""Определяет схемы URL для products."""

from django.urls import path
from . import views
from .views import MainPageView, ProductsListView, CatalogsListView

app_name = 'products'

urlpatterns = [
    # Домашняя страница
    # path('', views.main_page, name='main_page'),
    path('', MainPageView.as_view(), name='main_page'),
    # Страница каталога продуктов
    path('catalogs/', CatalogsListView.as_view(), name='catalogs'),
    path('products/<int:catalog_id>/', ProductsListView.as_view(), name='products'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    # Страница о магазине
    path('about_us/', views.about_us, name='about_us'),
    # Страница с контактами
    path('contacts/', views.contacts, name='contacts'),
    # Страница корзины
    path('basket/', views.basket, name='basket'),
    path('baskets/add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', views.basket_remove, name='basket_remove'),
]

MyDiplom/orders/models.py
from django.db import models
from users.models import User
from products.models import Basket

class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
    )

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(User, models.CASCADE)

    def __str__(self):
        return f'Order #{self.id}. {self.first_name} {self.last_name}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()

MyDiplom/orders/forms.py
from django import forms
from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Игорь'}))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Пупкин'}))
    email = forms.EmailField(label='Эл.почта', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'you@example.com'}))
    address = forms.CharField(label='Адрес', widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Россия, Сургут, ул. Ленина, дом 1',
    }))

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

MyDiplom/orders/views.py
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from orders.forms import OrderForm
from orders.models import Order
from django.shortcuts import render


class SuccessView(TemplateView):
    template_name = 'success.html'


class OrderCreateView(CreateView):
    template_name = 'order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:payment')

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


class OrderListView(ListView):
    template_name = 'orders.html'
    queryset = Order.objects.all()
    ordering = ('-created')

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'order.html'
    model = Order


def full_fill_order(request):
    orders = Order.objects.get_or_create(initiator=request.user, status=0)
    orders[0].update_after_payment()
    return render(request, 'payment.html')

MyDiplom/orders/templates/order-create.html
{% extends "base.html" %}

{% block content %}

<section>

    <div class="container">
        <div class="py-5 text-center">
            <h1>Оформление заказа</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Корзина</span>
                    <span class="badge badge-primary badge-pill text-white">{{ basket.total_quantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for basket in baskets %}
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">{{ basket.product.name }}</h6>
                            <small class="text-muted">{{ basket.quantity }} шт.</small>
                        </div>
                        <span class="text-muted">{{ basket.sum }} руб.</span>
                    </li>
                        {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Сумма к оплате</span>
                        <strong>{{ baskets.total_sum  }}</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Адрес доставки</h4>
                <form action="{% url 'orders:order_create' %}" method="post">

                    {% csrf_token %}
                    {{ form.as_p }}

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                </form>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

MyDiplom/orders/templates/order.html
{% extends "base.html" %}

{% block content %}

<section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказ #{{ object.id }}</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">Кол-во</th>
                            <th scope="col">Цена</th>
                            <th scope="col">Сумма</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for purchased_item in object.basket_history.purchased_items %}
                            <tr>
                                <th scope="row">
                                    {{ purchased_item.product_name }}
                                </th>
                                <td>{{ purchased_item.quantity }}</td>
                                <td>{{ purchased_item.price }} руб.</td>
                                <td>{{ purchased_item.sum }} руб.</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="float-right h4 mt-3">Итого {{ object.basket_history.total_sum }} руб.</p>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

MyDiplom/orders/templates/orders.html
{% extends "base.html" %}

{% block content %}

<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказы</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Создан</th>
                        <th scope="col">Итого</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in object_list %}

                    <tr>
                        <th scope="row">{{ order.id }}</th>
                        <td>{{ order.get_status_display }}</td>
                        <td>{{ order.created }}</td>
                        <td>{{ order.basket_history.total_sum }} руб.</td>
                        <td>
                            <a href="{% url 'orders:order' order.id %}">просмотреть</a>
                        </td>
                    </tr>

                    {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

MyDiplom/orders/templates/payment.html
{% extends "base.html" %}

{% block content %}

      <div class="row justify-content-center">

          	<h3 class="details">CREDIT CARD DETAILS</h3>
		<div class="card">

			<form action="#" method="post">
				<table> <!--frame="border" rules="all"-->
					<tr>
						<td>
							<label for="cardnumber">Card Number</label>
						</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td colspan="3">
							<input type="text" id="cardnumber" name="usercard" placeholder="1234 5678 9012 3456" />
						</td>
						<!--<td></td>-->
						<!--<td></td>-->
					</tr>
					<tr>
						<td>
							<label for="nameoncard">Name On Card</label>
						</td>
						<td></td>
						<td></td>
					</tr>
					<tr>
						<td colspan="3">
							<input type="text" id="nameoncard" name="username" placeholder="Name Surname" />
						</td>
						<!--<td></td>-->
						<!--<td></td>-->
					</tr>
					<tr>
						<td><label>Expiry Date</label></td>
						<td></td>
						<td><label for="cvv">CVV/CVN</label></td>
					</tr>
					<tr>
						<td>
							<select id="month" name="month" placeholder="02">
							<option>01</option>
							<option selected>02</option>
							<option>03</option>
							<option>04</option>
							<option>05</option>
							<option>06</option>
							<option>07</option>
							<option>08</option>
							<option>09</option>
							<option>10</option>
							<option>11</option>
							<option>12</option>
						</td>
						<td>
							<select id="year" name="year" placeholder="2017">
							<option>2017</option>
							<option>2018</option>
							<option>2019</option>
							<option>2020</option>
							<option>2021</option>
							<option>2022</option>
							<option>2023</option>
							<option>2024</option>
							<option>2025</option>

						</td>
						<td>
							<input type="text" id="cvv" placeholder="***" />
						</td>
					</tr>
				</table>
			</form>
		</div>

            <a class="btn btn-success btn-lg float-right" href="{% url 'orders:success' %}">
                Оплатить
            </a>
      </div>
{% endblock content %}

MyDiplom/orders/templates/success.html
{% extends "base.html" %}

{% block content %}

<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>
                                    Ваш заказ успешно сформирован.
                                </h4>
                                 <a class="btn btn-secondary btn-lg float-center" href="{% url 'products:catalogs' %}">
                                        продолжить покупки
                                 </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock content %}